### ISSUE TITLE
take_action_when_home_occupied.yaml trigger is wrong

### ISSUE THREAD

**Issue by genuineoleey** [jlpouffier/home-assistant-config#10]
Automation trigger in take_action_when_home_occupied.yaml blueprint should have swapped value of 0. Now it states:

```
trigger:
- platform: state
  entity_id:
  - !input zone_home
  to: '0'
  from:
```

But it should be:

```
trigger:
- platform: state
  entity_id:
  - !input zone_home
  from: '0'
  to:
```

When using take_action_when_home_occupied.yaml and take_action_when_home_empty.yaml together they both fire up at the same time as the conditions are the same but have swapped positions and not values.
