### ISSUE TITLE
fonction until ne fonctionne plus dans NOTIFIER

### ISSUE THREAD

**Issue by Rimfire03** [jlpouffier/home-assistant-config#3]
Bonjour,
Sans pouvoir être précis dans la date, je viens de me rendre compte que la fonction until  ne fonctionne plus dans NOTIFIER alors que cela fonctionné a merveille avant.
Une maj de HA n aurait pas fait apparaitre le bug ????

j ai remis la version du dépôt git de NOTIFIER juste au cas ou et le problème persiste.

voici un des exemple qui ne fonctionne pas:
```
action: send_when_present
message: Vous avez du courrier
title: Boite aux lettres
tag: lbox
until:
 - entity_id: input_boolean.hidden_courrier
   new_state: off
```

Bon courage
